name: Frontendeveloper CI / CD

on:
  push:

jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v2.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
    
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: eslint
        run: yarn lint:js

      # - name: unit-test
      #   run: yarn test

      - name: build nuxt
        run: yarn build
  deploy:
  
    runs-on: ubuntu-latest
    needs: setup

    permissions:
      contents: 'read'
      id-token: 'write'
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v2.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
    
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Build nuxt
        run: yarn build

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          activate_credentials_file: true
          service_account: 'frontendeveloper-front@appspot.gserviceaccount.com'
          project_id: 'frontendeveloper-front'
          workload_identity_provider: 'projects/421946401187/locations/global/workloadIdentityPools/frontendeveloper'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1' 
        with:
          deliverables: app.yaml
          project_id: frontendeveloper-front
          promote: true
          version: v1

      # Example of using the output
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'